### PR TITLE
Updating documentation and comments

### PR DESCRIPTION
**Pull request by BerkeAltiparmak**
This PR has updated the documentation since we now have Transcript as a separate entity and we have another use case called convertMultiWOZInteractor. You can find the updated documentation by double clicking ./documentation/global.html .

Because we have moved files while deploying, we have lost many files regarding JSDoc and other libraries I used for JSDoc templates. I fixed this issue and updated the documentation as described above. I've explicitly chosen to exclude test files in documentation, and we only document Use Case files as we discussed that it would be most meaningful.

### CODE REVIEW

**Comment by aidanmrli** [comment]
Could you please remove things like .DS_Store from the PR? Just remove them in a new commit.

**Review by aidanmrli — CHANGES_REQUESTED** [review]
I have viewed the files and they don't change any functionality of our program (we can see that all the tests pass too). I like the addition of new comments in multiple use-cases, that's great to see. The new documentation is up to date with our new use-case formats, which is fantastic.

Overall, I approve the merge! Let's just make sure that we don't include .DS_Store files in merges to main; they add clutter to the directory. Let's merge this tomorrow after a quick discussion.

**Comment by BerkeAltiparmak** [comment]
I can't find .DS_Store files in my folder since they are hidden (although when I force to display the hidden files, they still don't show up). I don't think changes in the .DS_Store files is a problem since most of them is a 0 byte change (so no change at all). I think we can merge this.

**Comment by BerkeAltiparmak** [comment]
Screen Shot 2022-12-08 at 23 56 33

**Pull request merged**
