### PR TITLE
Transcript is now an Entity

### PR DESCRIPTION
**Pull request by Dhairya-Khara**
As suggested by the TAs in our feedback, transcript should really be an entity to make our application more scalable. In this PR, I have used the approach we discussed after class with the TAs. Basically, Transcript is a sub document of the whole Schema. 

Changes are made in both the client and server reflect the changes.

### CODE REVIEW

**Comment by BerkeAltiparmak** [comment]
As mentioned in the group chat, the tests are failing. Let's keep this not merged until we fix the tests, to make sure nothing is broken.

**Comment by BerkeAltiparmak** [comment]
Great work Dhairya. The transcript indeed appears to be an entity now, and as we have confirmed earlier with the TAs, it being a Mongoose Schema is an acceptable Clean Architecture practice in this project.

**Comment by aidanmrli** [comment]
I have added some changes to the tests to reflect the updates to the transcripts, and have included mock functions in my tests to eliminate/reduce coupling between modules.

**Comment by aidanmrli** [comment]
Besides this, I think this is a good addition and will definitely help our project's scalability by explicitly specifying the Transcript's attributes as an Entity.

**Pull request merged**
