### PR TITLE
Finalizing UI Structure

### PR DESCRIPTION
**Pull request by krishnacheemalapati**
It's the moment we've all been waiting for: The finalized UI that we had on Figma, but implemented! Note that I still have some place-holder images on there, and I'll still need to create a few additional pages for the legal stuff, but that should be light work. I also plan on splitting up App.css so that it isn't a hot mess of 800+ lines of styling and divided amongst many files instead, but I just wanted to get this out there because I know y'all have been waiting for this for a while.

### CODE REVIEW

**Comment by Dhairya-Khara** [comment]
image

I am assuming on the left is a placeholder for an image. It will be great if you can find an image to place here and other similiar X boxes.

image
Let us not use California law and find something similiar to Ontario Law (as instructed by Michael)

image
Lets not include 30%. We can discuss a metric as a group to apply. We dont have anything to back it up yet and we will get grilled in the final presentation if we throw numbers like this.

image
Header should have Intentful instead of Techy Blinders. (Techy Blinders logo on the footer is ok)

image
The placeholder font seems to cutoff. I recommend just having 'Email' and 'Password' as placeholder texts.

image
Not a big fan of roles. I would prefer removing them. Great idea to incorporate the websites, github and linkedins though.

image
I dont think we should include the copyright notice on the dashboard. On the front page is fine.

There is also with the placement of the bubbles but no need to worry about it on this PR.

**Comment by Dhairya-Khara** [comment]
There are a lot of conflicts as well. Please resolve them.

**Comment by aidanmrli** [comment]
Great job Krish with the UI update; it's very ambitious! Having tested it, there are some bugs (might want to try merging in the latest commits from main before bugfixing as this may fix a few bugs):

1. When I logged in with a valid user and uploaded a new transcript that did not exist, a Not Authenticated error was thrown even though the transcript was uploaded successfully and can be visualized.
2. The pictures on the front/main page are not displaying, instead we have grey boxes with a cross
3. When visualizing all transcripts at once, the bubbles are too big and cut out at the top edge of the area allocated for visualization.

Still, I think this is a beautiful UI. Great job! Let's fix these bugs quickly and get the merge done before Thursday.

**Comment by Dhairya-Khara** [comment]
> 3\. When visualizing all transcripts at once, the bubbles are too big and cut out at the top edge of the area allocated for visualization.

@chenikabukes said she would work on that once the UI is merged.

**Comment by krishnacheemalapati** [comment]
To both Dhairya and Aidan's points about the images: Those are indeed just placeholders, we have "fakeFeature" and "fakeMain" as the source files for those. As I noted in my comments for the code, the plan is definitely to change those at some point, but since the UI with the graphs isn't fully finalized I just left those as is. I hope to make a gif for the main image that's like a montage of using the web app, and I can get a picture of the VoiceFlow intent block for the 2nd image, but until we've implemented Chenika's graph updates I'll leave the first feature image as is. 

As for the header, footer, placeholder text, and the blurb, you've got a good point Dhairya, I will change those. 

I would like to get the rest of the team's thoughts on roles before committing to removing them completely though. 

Also, I did merge main into my branch, but I guess more PRs have been merged into main since my PR has been opened, so I'll get on those. 

Thanks for reviewing this y'all, I'll get to work on these issues.

**Comment by chenikabukes** [comment]
Nice work Krishna! I agree with Dhairya about the roles. 
I would also prefer there not to be a copyright notice on the dashboard. 
With regards to color choices, I think it would be best if the upload transcript box is black and the bubbles are the same blue used throughout to bring some uniformity to the color palette. 
I think the "visualise all uploaded transcripts" button should look like the other buttons (blue and on hover white).
image
Overall great work Krishna!
Once the conflicts are resolved, I will commit the fix for the bubbles.

**Comment by chenikabukes** [comment]
Nice work on correcting everything Krishna! 
I fixed the bubble location so all should be working now!

**Comment by Dhairya-Khara** [comment]
Beautiful. I am going to merge this and escalate the changes to the production and build branches. Good work. We can discuss the images as a group.

**Pull request merged**
