### PR TITLE
Same filename issue

### PR DESCRIPTION
**Pull request by Dhairya-Khara**
Earlier, if the user uploads a file of the same name, they would see it on the dashboard even if the server was rejecting it. This was causing multiple errors on the client and the server being crashed. This is fixed now!

Another thing included in this PR is the bug where the server would crash if a file in incorrect format was uploaded (for eg. pdf). The same error messages is displayed in either cases.

### CODE REVIEW

**Comment by BerkeAltiparmak** [comment]
This doesn't seem to be working for me.
When I first log in with a new account, I get an error for uploading a transcript (which is weird because I've just logged in). This is a minor issue.
When I try to upload a x.json file, it gives me an error even though I don't have a transcript uploaded.
@Dhairya-Khara could you check if you forgot to commit something? If it seems to be working on your end, someone else should review this PR as well to confirm it working, because I might have done something wrong as well.

**Comment by aidanmrli** [comment]
This is working for me! An error is thrown correctly when uploading a file with the same name as an already existing file for one user. The error is "Error uploading file". I would add slightly more detail to the error message by adding that the error is because a file of the same name already exists. This would help us adhere to Principle 3: Simple and Intuitive Use from the Principles of Universal Design from the Ethics modules.

**Comment by Dhairya-Khara** [comment]
> This is working for me! An error is thrown correctly when uploading a file with the same name as an already existing file for one user. The error is "Error uploading file". I would add slightly more detail to the error message by adding that the error is because a file of the same name already exists. This would help us adhere to Principle 3: Simple and Intuitive Use from the Principles of Universal Design from the Ethics modules.

Great feedback Aidan. I have applied the principles and now we get custom error messages. So if a user uploads a file with the same name, the error will say "A transcript with the same name already exists". Furthermore, if a user uploads a file in an invalid format, the error will say "Invalid Format"

**Comment by aidanmrli** [comment]
Perfect! This passes our CI build checks and is good to merge to main.

**Pull request merged**
